### ISSUE TITLE
SidebySideView for RT4.2.9

### ISSUE THREAD

**Issue by nitinkumar521** [tbrumm/RT-Extension-SideBySideView#1]
Hello, This is great Extension and I have bee tweaking to try to work with RT 4.2.9 but unfortunately have not been successful so far. 

If you have time can you please update the code to work with RT 4.2.9. It looks like the Transactions and Attachments hooks have been implemented differently with RT version 4.2.9

Any support will be greatly appreciated.

Best
Nitin Kumar

**Comment by tbrumm** [comment]
Is on my list for this week, had some other requests already. will try to fix it asap.

torsten

**Comment by nitinkumar521** [comment]
Great ! Thanks.

**Comment by tbrumm** [comment]
Hi,
i have fixed this for the latest RT 4.2.9 from BPS Git Repo of RT. Please test

**Comment by nitinkumar521** [comment]
Thank you very much. Just tried and it works perfectly.

Thanks again for a very quick response.

**Comment by tbrumm** [comment]
:-) Your are welcome, hope you enjoy it :-))
