### ISSUE TITLE
Extension doesnt work with RT 4.4.3 anymore cleanly

### ISSUE THREAD

**Issue by tbrumm** [tbrumm/RT-Extension-SideBySideView#2]
![2018-11-30 07_18_38- 129901887_ pretask_ request tracker-request-scripts - ticket int kn - user de](https://user-images.githubusercontent.com/149292/49272030-538c0580-f470-11e8-948b-ae11f72d0e5f.png)

**Comment by netsandbox** [comment]
Looks good for me on a vanilla RT 4.4.3 and only this extension installed and active:
![bildschirmfoto vom 2018-11-30 um 11 27 57](https://user-images.githubusercontent.com/165430/49283908-50564100-f493-11e8-8b7b-f1396bc351c2.png)

So it's a problem with another extension, which modifies the page layout.

**Comment by tbrumm** [comment]
Hi Chris,
sure, we have tested it also inside vanilla RT Config, but if we turn off Reminders (Set($EnableReminders, 1); -> Set($EnableReminders, 0);) it will break!

Torsten

**Comment by netsandbox** [comment]
Disabling reminders was the part that was missing to reproduce the issue.
By the way, this isn't only a problem in RT 4.4, also in RT 4.2 is the layout broken.
I will lock into it.

**Comment by netsandbox** [comment]
Please test with commit  4cc767c
